### ISSUE TITLE
when i open mc with this mod pack i get 10 or some times 20fps

### ISSUE THREAD

**Issue by doginahoodie** [Sotumney/IceBoatRacingModpack#12]
For some reason im getting 10 fps even if i change the render distance and i dont think its a specs issue as i have a r5 3600 with an rtx2060

**Comment by Sotumney** [comment]
Please refer to #9 on how to create a proper issue, reports such as these will be ignored

**Comment by doginahoodie** [comment]
how is this not a proper report if thats all thats all wth

**Comment by Sotumney** [comment]
> how is this not a proper report if thats all thats all wth

I get that but I really need this screen for any diagnostics when it comes to system performance / driver related issues :(
![image](https://github.com/user-attachments/assets/2aa59c25-2d92-4ccd-8678-7215730f31ba)
